### ISSUE TITLE
[Feature] AI Spawn Module in Zeus

### ISSUE THREAD

**Issue by MitchJC793** [last-resort-gaming/LRG-Fundamentals#13]
**Is your feature request related to a problem? Please describe.**
AI Spawn module could be more useful if functionality could also be used in Zeus.

**Describe the solution you'd like**
Add a Zeus Option for LRG AI Spawn that allows the curator to place the module and populate an area in game.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by m0kka** [comment]
done some time ago
