### ISSUE TITLE
[Bug] Medical Module does not work on my Dedicated Server

### ISSUE THREAD

**Issue by arismagicgr** [last-resort-gaming/LRG-Fundamentals#42]
**Describe the bug**
I set the medical module and I sync it with a deconatmination tent object. When I go inside the tent injured nothing happens, no healing at all.

**To Reproduce**
1. Place Module '....'
2. Enable Mode '....'
3. Play in MP '....'
4. Error "..."
I couldn't reproduce the problematic behaviour because when I tried to do it on editor and tried it it worked perfectly fine. I even tried it with all the mods that I use loaded!

**Expected behaviour**
Expected to be fully healed but nothing happened!

**Screenshots**
The screenshots are from the set up of the module and the object.
![107410_20191006203728_1](https://user-images.githubusercontent.com/50752327/66277068-e45a1b80-e8a1-11e9-9dbe-1032221ecc5e.png)
![107410_20191006203740_1](https://user-images.githubusercontent.com/50752327/66277069-e4f2b200-e8a1-11e9-8c43-7f15f9e22c93.png)
![107410_20191006203752_1](https://user-images.githubusercontent.com/50752327/66277070-e4f2b200-e8a1-11e9-9ba7-a95522c4961b.png)

**Additional context**
I will send you the .pbo, the .html with the modlist and the the .txt with the addon settings that I used on discord because here .pbos and .htmls are not supported. The files will be named "ALiVE Tanoa.xxx"

**Comment by MitchJC793** [comment]
Medical Facility function has been updated to the new ACE function as well as changes to how the function is called. We ran tests on this today and had a 100% success rate. If you have any further issues with this, place raise another ticket.
